name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # main 브랜치에 push하면 배포 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t ${{ DOCKER_HUB_USERNAME }}/${{ DOCKER_IMAGE_NAME }}:latest .

      # 3️⃣ Docker Hub 로그인
      - name: Log in to Docker Hub
        run: echo "${{ DOCKER_HUB_PASSWORD }}" | docker login -u "${{ DOCKER_HUB_USERNAME }}" --password-stdin

      # 4️⃣ Docker Hub에 이미지 푸시
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ DOCKER_HUB_USERNAME }}/${{ DOCKER_IMAGE_NAME }}:latest

      # 5️⃣ AWS Credentials 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ AWS_REGION }}

      # 6️⃣ Elastic Beanstalk 배포
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ AWS_EB_ENV_NAME }} \
            --version-label "deploy-${{ github.run_number }}"
